---
- name: Ensure {{ backup_data_path }} directory exists
  ansible.builtin.file:
    path: "{{ backup_data_path }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: copy hivemq backup script
  ansible.builtin.template:
    src: backup.sh
    dest: "{{ backup_data_path }}/backup.sh"
    owner: root
    group: root
    mode: "0744"

- name: Ensure /var/spool/cron directory exists
  ansible.builtin.file:
    path: /var/spool/cron
    state: directory

- name: Create hivemq backup cronjob
  ansible.builtin.cron:
    minute: "0"
    hour: "1"
    name: "Backup HiveMQ"
    job: "/bin/bash {{ backup_data_path }}/backup.sh"
