---
- name: Prepare
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install cron
      ansible.builtin.apt:
        name: cron
        cache_valid_time: 3600
